version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
hooks:
  BeforeInstall:
    - location: requirements.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /home/ec2-user/start.sh
      timeout: 300
      runas: root

