version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: requirements.sh
    - location: start.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./execStart.sh
      timeout: 300
      runas: root

